# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-22 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalipn',
            name='address_country_code',
            field=models.CharField(blank=True, help_text='ISO 3166', max_length=64),
        ),
        migrations.AlterField(
            model_name='paypalipn',
            name='auction_closing_date',
            field=models.DateTimeField(blank=True, help_text='HH:MM:SS DD Mmm YY, YYYY PST', null=True),
        ),
        migrations.AlterField(
            model_name='paypalipn',
            name='business',
            field=models.CharField(blank=True, help_text='Email where the money was sent.', max_length=127),
        ),
        migrations.AlterField(
            model_name='paypalipn',
            name='case_creation_date',
            field=models.DateTimeField(blank=True, help_text='HH:MM:SS DD Mmm YY, YYYY PST', null=True),
        ),
        migrations.AlterField(
            model_name='paypalipn',
            name='currency_code',
            field=models.CharField(blank=True, default='USD', max_length=32),
        ),
        migrations.AlterField(
            model_name='paypalipn',
            name='mc_currency',
            field=models.CharField(blank=True, default='USD', max_length=32),
        ),
        migrations.AlterField(
            model_name='paypalipn',
            name='next_payment_date',
            field=models.DateTimeField(blank=True, help_text='HH:MM:SS DD Mmm YY, YYYY PST', null=True),
        ),
        migrations.AlterField(
            model_name='paypalipn',
            name='parent_txn_id',
            field=models.CharField(blank=True, max_length=19, verbose_name='Parent Transaction ID'),
        ),
        migrations.AlterField(
            model_name='paypalipn',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='HH:MM:SS DD Mmm YY, YYYY PST', null=True),
        ),
        migrations.AlterField(
            model_name='paypalipn',
            name='retry_at',
            field=models.DateTimeField(blank=True, help_text='HH:MM:SS DD Mmm YY, YYYY PST', null=True),
        ),
        migrations.AlterField(
            model_name='paypalipn',
            name='subscr_date',
            field=models.DateTimeField(blank=True, help_text='HH:MM:SS DD Mmm YY, YYYY PST', null=True),
        ),
        migrations.AlterField(
            model_name='paypalipn',
            name='subscr_effective',
            field=models.DateTimeField(blank=True, help_text='HH:MM:SS DD Mmm YY, YYYY PST', null=True),
        ),
        migrations.AlterField(
            model_name='paypalipn',
            name='time_created',
            field=models.DateTimeField(blank=True, help_text='HH:MM:SS DD Mmm YY, YYYY PST', null=True),
        ),
        migrations.AlterField(
            model_name='paypalipn',
            name='txn_id',
            field=models.CharField(blank=True, db_index=True, help_text='PayPal transaction ID.', max_length=19, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='paypalipn',
            name='txn_type',
            field=models.CharField(blank=True, help_text='PayPal transaction type.', max_length=128, verbose_name='Transaction Type'),
        ),
    ]
