# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-22 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalnvp',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='paypalnvp',
            name='countrycode',
            field=models.CharField(blank=True, max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='paypalnvp',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='paypalnvp',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='paypalnvp',
            name='state',
            field=models.CharField(blank=True, max_length=255, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='paypalnvp',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='paypalnvp',
            name='zip',
            field=models.CharField(blank=True, max_length=32, verbose_name='Postal / Zip Code'),
        ),
    ]
